/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-corolla-ae86-trueno-fe02fba6302e450ea8424591493341ea
Title: Toyota Corolla AE86 Trueno
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HakurochiFaster(props) {
  const { nodes, materials } = useGLTF('/toyota_corolla_ae86_trueno.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.035, 0, 0]} scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.011']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Material.013']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials['Material.014']}
        />
      </group>
      <group position={[1.672, -0.25, -2.991]} scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group
        position={[-1.607, -0.25, -2.991]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group position={[1.672, -0.266, 2.523]} scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group
        position={[-1.607, -0.266, 2.523]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials['Material.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials['Material.020']}
        />
      </group>
      <group scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_30.geometry}
          material={materials.fpostersmallwall_textureproduct750x1000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials['Material.010']}
        />
      </group>
      <group scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.fpostersmallwall_textureproduct750x1000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials['Material.010']}
        />
      </group>
      <group position={[0.014, 0, 0]} scale={[0.26, 0.307, 0.26]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_38.geometry}
          material={materials['tofu_shop.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials['Material.034']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials['Material.002']}
        scale={[0.26, 0.307, 0.26]}
      />
    </group>
  )
}

useGLTF.preload('/toyota_corolla_ae86_trueno.glb')



